# Generated by Django 5.0.3 on 2024-03-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_todo_date_alter_todo_isdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Нэр', models.CharField(max_length=50)),
                ('Тайлбар', models.CharField(max_length=200)),
                ('Огноо', models.DateTimeField(auto_now_add=True)),
                ('Хаяг', models.CharField(max_length=200)),
                ('Мөнгө', models.CharField(max_length=50)),
            ],
        ),
    ]
